# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Publish to Nuget
on:
  push:
    branches:
      - 'master'
jobs:
  build:

    runs-on: ubuntu-latest
    env:
      VERSION: 0.${{ github.run_number }}

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --configuration Release /p:Version=${{ env.VERSION }}
      
    - name: Test
      run: dotnet test --configuration Release /p:Version=${{ env.VERSION }} --no-build
      
    - name: Pack with custom version
      run: dotnet pack --configuration Release --no-build --output nupkgs/ -p:PackageVersion=${{ env.VERSION }}-prerelease

    - name: Upload NuGet artifacts
      uses: actions/upload-artifact@v2
      with:
        name: NuGet-Packages
        path: nupkgs/
